import { StyleSheet } from 'react-native';
import { colors } from '@/constants/colors';

export const contactsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.navy,
  },
  body: {
    flex: 1,
  },
  header: {
    backgroundColor: colors.navy,
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 26,
    position: 'relative',
    overflow: 'hidden',
  },
  headerGlow: {
    position: 'absolute',
    top: -30,
    right: -30,
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: colors.amber,
    opacity: 0.12,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  greetText: {
    color: 'rgba(255,255,255,0.55)',
    fontSize: 12,
    fontWeight: '500',
    marginBottom: 3,
  },
  titleText: {
    color: colors.white,
    fontSize: 24,
    fontWeight: '800',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 8,
  },
  headerBtn: {
    width: 38,
    height: 38,
    backgroundColor: 'rgba(245,159,10,0.18)',
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chips: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 4,
    gap: 8,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1.5,
  },
  chipActive: {
    backgroundColor: colors.navy,
    borderColor: colors.navy,
  },
  chipInactive: {
    backgroundColor: colors.white,
    borderColor: colors.border,
  },
  chipTextActive: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '700',
  },
  chipTextInactive: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  searchWrap: {
    marginHorizontal: 16,
    marginVertical: 10,
    position: 'relative',
  },
  searchIcon: {
    position: 'absolute',
    left: 14,
    top: '50%',
    transform: [{ translateY: -8 }],
    zIndex: 1,
  },
  searchInput: {
    width: '100%',
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 14,
    paddingVertical: 12,
    paddingLeft: 42,
    paddingRight: 44,
    fontSize: 13,
    color: colors.text,
    shadowColor: colors.text,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  searchFilter: {
    position: 'absolute',
    right: 10,
    top: '50%',
    transform: [{ translateY: -16 }],
    width: 32,
    height: 32,
    backgroundColor: colors.navy,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  countBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 6,
    paddingBottom: 10,
  },
  countText: {
    fontSize: 12,
    color: colors.muted,
    fontWeight: '500',
  },
  countStrong: {
    color: colors.text,
    fontWeight: '800',
  },
  sortBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  sortText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.amberDark,
  },
  contactList: {
    paddingHorizontal: 16,
    gap: 10,
    paddingBottom: 14,
  },
  contactCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 13,
    shadowColor: colors.text,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
    position: 'relative',
    overflow: 'hidden',
  },
  contactCardActive: {
    transform: [{ scale: 0.98 }],
  },
  contactBar: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: colors.amber,
    opacity: 0,
  },
  contactAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contactAvatarText: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.white,
  },
  contactBody: {
    flex: 1,
  },
  contactName: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.text,
  },
  contactRole: {
    fontSize: 11,
    color: colors.muted,
    fontWeight: '500',
    marginTop: 1,
  },
  contactCompany: {
    fontSize: 11,
    color: colors.amberDark,
    fontWeight: '700',
    marginTop: 1,
  },
  contactDetails: {
    marginTop: 8,
    gap: 4,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  contactRowText: {
    fontSize: 11,
    color: colors.muted,
    fontWeight: '500',
    flex: 1,
  },
  contactTags: {
    flexDirection: 'row',
    gap: 5,
    flexWrap: 'wrap',
    marginTop: 8,
  },
  tag: {
    paddingVertical: 3,
    paddingHorizontal: 9,
    borderRadius: 20,
    fontSize: 9,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    overflow: 'hidden',
  },
  contactRight: {
    alignItems: 'flex-end',
    gap: 6,
  },
  contactDate: {
    fontSize: 9,
    color: colors.textLight,
    fontWeight: '600',
  },
  contactMore: {
    width: 28,
    height: 28,
    backgroundColor: colors.bg,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
});