import { Platform, StyleSheet } from 'react-native';
import { colors } from '@/constants/colors';

export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.phoneBg,
  },
  scrollView: {
    flex: 1,
  },
    scrollViewContent: {
    flexGrow: 1,
    paddingBottom: Platform.OS === 'ios' ? 40 : 20,
  },
  toast: {
    position: 'absolute',
    top: 54,
    alignSelf: 'center',
    backgroundColor: colors.toastBg,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 999,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  toastText: {
    color: colors.white,
    fontWeight: '700',
    fontSize: 12,
    marginLeft: 7,
  },
  hero: {
    backgroundColor: colors.navy,
    paddingHorizontal: 28,
    paddingTop: 20,
    paddingBottom: 48,
    position: 'relative',
  },
  heroGlow: {
    position: 'absolute',
    top: -80,
    right: -80,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: 'rgba(245,159,10,0.22)',
  },
  brand: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  brandIcon: {
    width: 42,
    height: 42,
    backgroundColor: colors.amber,
    borderRadius: 13,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    shadowColor: colors.amber,
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  brandName: {
    color: colors.white,
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  brandTag: {
    color: colors.amber,
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  heroTitle: {
    color: colors.white,
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
    marginBottom: 8,
  },
  heroSpan: {
    color: colors.amber,
  },
  heroSub: {
    color: 'rgba(255,255,255,0.55)',
    fontSize: 13,
    fontWeight: '500',
    marginBottom: 28,
  },
  tabs: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 14,
    padding: 4,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
  activeTab: {
    backgroundColor: colors.amber,
    shadowColor: colors.amber,
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 4,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.45)',
  },
  activeTabText: {
    color: colors.navy,
  },
  card: {
    backgroundColor: colors.white,
    marginHorizontal: 16,
    marginTop: -20,
    borderRadius: 24,
    padding: 22,
    shadowColor: colors.navy,
    shadowOpacity: 0.12,
    shadowRadius: 40,
    elevation: 8,
  },

  inputGroup: {
    marginBottom: 14,
  },
  label: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bg,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 13,
  },
  inputIcon: {
    marginRight: 8,
  },
  input: {
    flex: 1,
    paddingVertical: 13,
    fontSize: 14,
    color: colors.text,
    fontWeight: '500',
  },
  options: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  remember: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 5,
    backgroundColor: colors.bg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checked: {
    backgroundColor: colors.amber,
    borderColor: colors.amber,
  },
  rememberText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.muted,
  },
  forgotLink: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.amberDark,
  },
  btn: {
    backgroundColor: colors.amber,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    borderRadius: 14,
    gap: 8,
    marginBottom: 14,
    shadowColor: colors.amber,
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 6,
  },
  btnText: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.navy,
  },
  switchLink: {
    textAlign: 'center',
    fontSize: 12,
    color: colors.muted,
    fontWeight: '500',
  },
  row: {
    flexDirection: 'row',
    gap: 10,
  },
  strengthRow: {
    flexDirection: 'row',
    gap: 4,
    marginTop: 6,
  },
  strengthBar: {
    height: 3,
    flex: 1,
    backgroundColor: colors.border,
    borderRadius: 4,
  },
  strengthActive: {
    backgroundColor: colors.amber,
  },
  backLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 20,
  },
  backText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.muted,
  },
  forgotIcon: {
    width: 60,
    height: 60,
    backgroundColor: colors.amberLight,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 14,
  },
  forgotTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.navy,
    textAlign: 'center',
    marginBottom: 6,
  },
  forgotSub: {
    fontSize: 12,
    color: colors.muted,
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 18,
  },
  bottomInfo: {
    padding: 20,
    paddingHorizontal: 24,
  },
  bottomText: {
    fontSize: 10,
    color: colors.muted,
    fontWeight: '500',
    lineHeight: 16,
    textAlign: 'center',
  },
  bottomLink: {
    color: colors.amberDark,
    fontWeight: '600',
  },
});